import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/Sidebar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Commander's Dashboard",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <div className="flex flex-row min-h-screen">
      <div className="flex-grow overflow-y-auto">
        {children}
      </div>
    </div>
    </body>
    </html>
  )
}
